# This file is generated by packaging/homebrew/render_formula.sh in
# https://github.com/umutarmut38/council. Do not edit by hand.
class CouncilAT100Preview1 < Formula
  desc "Multi-agent orchestration TUI for competing AI coding-agent CLIs"
  homepage "https://github.com/umutarmut38/council"
  version "1.0.0-preview.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v1.0.0-preview.1/council_v1.0.0-preview.1_darwin_arm64.tar.gz"
      sha256 "025c7fca60cb7e10f958ae0047faec551ab7a76053c47d78db3c339da06e4172"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v1.0.0-preview.1/council_v1.0.0-preview.1_darwin_amd64.tar.gz"
      sha256 "5240b3e9e4b56f60c50c2575270f61130c0e2de28e08a3ccd437aee64980ca58"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v1.0.0-preview.1/council_v1.0.0-preview.1_linux_arm64.tar.gz"
      sha256 "a7c547390fabc9f193723355095c092aa2f69541712f757e21ef7720d11285b3"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v1.0.0-preview.1/council_v1.0.0-preview.1_linux_amd64.tar.gz"
      sha256 "b8cba6ce74c634e5409535b2418524827be496322035f85f5f3c9c91a6adce87"
    end
  end

  def install
    bin.install "council"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/council version")
  end
end
