# This file is generated by packaging/homebrew/render_formula.sh in
# https://github.com/umutarmut38/council. Do not edit by hand.
class Council < Formula
  desc "Multi-agent orchestration TUI for competing AI coding-agent CLIs"
  homepage "https://github.com/umutarmut38/council"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v0.3.0/council_v0.3.0_darwin_arm64.tar.gz"
      sha256 "bf0a787f96b3b7a5f43eb7867bd6b0d382590b376478c37c2b71916b089bd8d6"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v0.3.0/council_v0.3.0_darwin_amd64.tar.gz"
      sha256 "6d22d5a88025f24d8488c1f38eab348bb57d59dc024023c5790e3f0faf5a341a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v0.3.0/council_v0.3.0_linux_arm64.tar.gz"
      sha256 "e1cc4408fc4585bbb635826163ebfd6a9b3fdbc8e3a0b27801fc8157ee14afbe"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v0.3.0/council_v0.3.0_linux_amd64.tar.gz"
      sha256 "cb3bb158943dd52d8bb631522a54454ad7d51f53737a35d7b55244d74e0b484a"
    end
  end

  def install
    bin.install "council"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/council version")
  end
end
