# This file is generated by packaging/homebrew/render_formula.sh in
# https://github.com/umutarmut38/council. Do not edit by hand.
class Council < Formula
  desc "Multi-agent orchestration TUI for competing AI coding-agent CLIs"
  homepage "https://github.com/umutarmut38/council"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v0.2.0/council_v0.2.0_darwin_arm64.tar.gz"
      sha256 "63d9377e09c5910466e8fae4f2dff16c7fefe8dae8b0595e3e82784ca3cfe43e"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v0.2.0/council_v0.2.0_darwin_amd64.tar.gz"
      sha256 "0c82ad718d40db424787327b9876a2f508bddc130dbef4a0ab27e9488f36ed83"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/umutarmut38/council/releases/download/v0.2.0/council_v0.2.0_linux_arm64.tar.gz"
      sha256 "04912c5a698269562569bc22040872d46c6cbd493eb1a0e4252839dd1f7c4d07"
    end
    on_intel do
      url "https://github.com/umutarmut38/council/releases/download/v0.2.0/council_v0.2.0_linux_amd64.tar.gz"
      sha256 "08f054a6d4c810d9757b865e86a615e4a83b13c62930c77c0ee89e8960964489"
    end
  end

  def install
    bin.install "council"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/council version")
  end
end
